# Generated by Django 4.1.7 on 2023-03-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_additional_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="photos/avatar-user-64.png",
                upload_to="photos/",
                verbose_name="Photo",
            ),
        ),
    ]
